__version__ = "1.0.4"
__author__ = "Job Snijders"
__author_email__ = "job@ntt.net"
__copyright__ = "Copyright 2018-2019, Job Snijders"
__license__ = "BSD 2-Clause"
__status__ = "Stable"
__url__ = "https://github.com/job/ripe-proposal-2018-06"
